on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  update_wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest merged pull requests
        id: fetch_prs
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&per_page=10")
          
          # Filter for merged PRs
          merged_prs=$(echo "$response" | jq -r 'map(select(.merged_at != null)) | .[] | "PR: \(.title) - \(.html_url)\nDescription: \(.body)"')
          echo "::set-output name=prs::${merged_prs}"

      - name: Update wiki
        run: |
          CONTENT="### Latest Merged Pull Requests\n\n${{ steps.fetch_prs.outputs.prs }}"
          
          # Update the homepage of the wiki
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"content\": \"${CONTENT}\"}" \
            "https://api.github.com/repos/${{ github.repository }}/wiki/Home"
