name: Update Wiki with Latest PRs

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest merged pull requests
        id: fetch_prs
        run: |
          response=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&per_page=10")

          merged_prs=$(echo "$response" | jq -r 'map(select(.merged_at != null)) | .[] | "PR: \(.title) - \(.html_url)\nDescription: \(.body)"')

          if [ -z "$merged_prs" ]; then
            echo "No merged PRs found."
            exit 1
          fi

          echo "prs<<EOF" >> $GITHUB_ENV
          echo "$merged_prs" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Prepare wiki content
        id: prepare_content
        run: |
          CONTENT="### Latest Merged Pull Requests\n\n${{ env.prs }}"
          echo "content=${CONTENT}" >> $GITHUB_ENV

      - name: Update wiki
        uses: OrlovM/Wiki-Action@v1
        with:
          path: 'wiki'  # Directory containing your wiki files
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update wiki with latest merged PRs"
          filename: 'Latest_Merged_PRs.md'  # Name of the wiki page to update
          content: ${{ env.content }}  # Content fetched and prepared
