name: Update Wiki Page with PRs

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wiki repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}.wiki
        path: wiki

    - name: Add header to the wiki page
      run: |
        echo "# Latest Pull Requests" > wiki/test.md
        echo "" >> wiki/test.md # Optionally add a new line for spacing
        curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&sort=updated&direction=desc&per_page=10" \
          | jq -r '.[] | "- [#\(.number)] - \(.title)[Link](\(.html_url))\n  \(.body)"' >> wiki/test.md
          
    - name: Configure Git
      run: |
        cd wiki
        git config user.name "GitHub Actions"
        git config user.email "action@github.com"

    - name: Commit and push changes
      run: |
        cd wiki
        git add test.md
        git commit -m "Update test.md with latest pull requests"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
